SET SQL_SAFE_UPDATES = 0; -- SAFE MODE 끄기

#UPDATE tbl_supplier_temp SET REG_ID = NULL;

# 테이블 A, 테이블 B
UPDATE tbl_supplier_temp TEMP, tbl_region R
# 데이터 수정
SET TEMP.REG_ID = R.REG_ID
# 
WHERE TEMP.REGION = R.REGION AND TEMP.SUBREGION = R.SUBREGION;


SET SQL_SAFE_UPDATES = 1; -- SAFE MODE 켜기

-- select * from tbl_region;

SELECT DISTINCT REG_ID, REGION, REGION_ORI, SUBREGION, SUBREGION_ORI  FROM tbl_supplier_temp ORDER BY REGION_ORI, SUBREGION_ORI LIMIT 10000;

SELECT DISTINCT REG_ID, REGION, REGION_ORI, SUBREGION, SUBREGION_ORI  FROM tbl_supplier_temp WHERE REG_ID IS NULL;